### ISSUE TITLE
Error Run System without ROI

### ISSUE THREAD

**Issue by Arbow404** [riochandra1212/object-detection-app#2]
python version 3.8
opencv version 4.5

D:/praktikum/latihan/object-detection-app/surveillance.m4v
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Who Am i\AppData\Local\Programs\Python\Python38\lib\tkinter\_init.py", line 1883, in __call_
    return self.func(*args)
  File "D:\praktikum\latihan\object-detection-app\TA2020.py", line 104, in runDetector
    self.detectorVideo()
  File "D:\praktikum\latihan\object-detection-app\TA2020.py", line 131, in detectorVideo
    self.updateDetectorVideo()
  File "D:\praktikum\latihan\object-detection-app\TA2020.py", line 136, in updateDetectorVideo
    result = self.brain_tracker.track_object_inframe(
  File "D:\praktikum\latihan\object-detection-app\brainTracker.py", line 27, in track_object_inframe
    self.check_objects_trough_ROI()
  File "D:\praktikum\latihan\object-detection-app\brainTracker.py", line 190, in check_objects_trough_ROI
    if self.is_trough_ROI(self.objects_tracked[i]) == True:
  File "D:\praktikum\latihan\object-detection-app\brainTracker.py", line 195, in is_trough_ROI
    return self.is_inside_box(self.box_ROI, obj[2])
  File "D:\praktikum\latihan\object-detection-app\brainTracker.py", line 66, in is_inside_box
    parent[x], parent[y], parent[w], parent[h] = parent_box
TypeError: cannot unpack non-iterable NoneType object
[Finished in 21.4s]

**Comment by RioChndr** [comment]
Ini file videonya ? `D:/praktikum/latihan/object-detection-app/surveillance.m4v`

Error ini muncul ketika menjalankan perintah pertama kali atau saat masukin foto/video ?

**Comment by Arbow404** [comment]
iya itu video nya bang
jadi solusi nya bagaimana bang

**Comment by Arbow404** [comment]
apakah perlu download lagi

**Comment by Arbow404** [comment]
untuk format video nya di sintax nya sudah saya tambahkan m4v

**Comment by RioChndr** [comment]
Perintah yg kamu jalnakan, perintah apa ?

coba jalankan perintah `python TA2020.py`

**Comment by Arbow404** [comment]
saya menjalankan nya pake sublime, perintah yg saya jalankan TA2020.py

**Comment by Arbow404** [comment]
![image](https://user-images.githubusercontent.com/71306038/115505497-c1386680-a2a3-11eb-8f32-50b129433b8c.png)

masih eror bang

**Comment by Arbow404** [comment]
saya liat youtube nya lagi, di setting roi nya berubah jadi atur roi bang. tetapi di source code ga ada tulisan atur roi bang.

**Comment by RioChndr** [comment]
![image](https://user-images.githubusercontent.com/22429169/115505926-65baa880-a2a4-11eb-90af-e279bd06defd.png)

yak, saya jumpa error yang sama.

**Comment by RioChndr** [comment]
Sistem ini masih sangat premature, kamu perlu setting ROInya dulu, dengan **klik tombol "Setting ROI"** lalu muncul jendela baru, kemudian buat kotak ROI didalam jendela tsb dengan cara klik dan drag didalamnya. kemudian tekan **enter**, barulah klik tombol "RUN"

Jika tidak seperti itu, sistem akan error seperti diatas.

**Comment by Arbow404** [comment]
Alhamdulilah running bang. 

kalo biar ada tombol start/pause nya seperti di yotube itu gimana yah bang

**Comment by Arbow404** [comment]
bang kalo video nya running lambat itu karna apa yah apakah faktor dari laptop nya atau ada faktor lain??

**Comment by Arbow404** [comment]
bang kalo video nya running lambat itu karna apa yah apakah faktor dari laptop nya atau ada faktor lain??

**Comment by RioChndr** [comment]
Aplikasi ini belum ada tombol pause/stopnya, karena masih sangat baru dan saya sudah lama tidak kembangkan aplikasi ini. kalau kamu bisa memperbaiki aplikasinya, dengan senang hati pull request ke repo ini agar jadi lebih baik.

Kenapa video runningnya lambat, karena YOLOV3 itu menggunakan algoritma deep learning yang membutuhkan komputasi yang cukup tinggi, pada laptop biasa menjaalankan algoritma ini akan jadi sangat lambat.

**Comment by Arbow404** [comment]
baik bang akan saya coba dan pelajari terlebih dahulu. 
iya bang agak macet2 dikit td, tapi tidak apa2 bang. oke deh bang terima kasih atas ilmu nya semoga channel nya terus maju, di tunggu video2 lain nya. maaf bang udah ganggu waktu nya
